# User Settings | Edit there as per required

title: Inspired Space
url: "https://inspiredspace.blog/"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    inspired<span class = "faded">space.blog</span>

email: astrophysicsnews@gmail.com
author: Robert James
# This description will show up in google search results
# (for index page) etc.
description: >
    Fresh, easy perspectives on space topics.

# This will what will show against &copy; in the footer
copyright: robertcjames
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
   easy <span>astrophysics and space</span> summaries 
# <a class="underline different-highlight" href="http://ankitsultana.com/accent/documentation.html">
#    Browse our blogs
# </a>
# to get started.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Writing easy articles on space that even I can understand.

about_footer: true

twitter_username: InspiredSpace_
github_username: R221
facebook_id: yourusername

favicon: true
favicon_location: "images/favicon_1_8HY_icon.ico"

profile_picture: images/profilepic.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/twitter_profile_pic.png" # This will show in facebook thumbnails
twitter_image: "https://twitter.com/InspiredSpace_" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
