# User Settings | Edit there as per required

title: astrophysics blog
url: "https://r221.github.io/accent"
baseurl: "/accent"

# This will show up at the top of index page
site_heading: >
    astrophysics blog

email: astrophysicsnews@gmail.com
author: Robert James
# This description will show up in google search results
# (for index page) etc.
description: >
    an astrophysics blog by Robert James and Karim Alexander

# This will what will show against &copy; in the footer
copyright: robertcjames
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro:          # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
   easy <span>astrophysics and space</span> summaries. 
   # <a class="underline different-highlight" href="http://ankitsultana.com/accent/documentation.html">
    #    Browse our blogs
     #</a>
    #to get started.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    astrophysics for all.

about_footer: true

twitter_username: robertspacej
github_username: R221
facebook_id: yourusername

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.com/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
